import Head from 'next/head';
import Contact from '../components/contact';
import Experience from '../components/experience';
import Expertise from '../components/expertise';
import Intro from '../components/intro';
import Navbar from '../components/navbar';
import Projects from '../components/projects';
import Testimonials from '../components/testimonials';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Navbar />
        <Intro />
        <div className="px-[5vw]">
          <Expertise />
          <Experience />
          <Projects />
          <Testimonials />
          <Contact />
        </div>
      </main>
    </div>
  );
}
